# Generated by Django 5.2.13 on 2026-05-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comunidad_rol_tipovariable_remove_command_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturasensor',
            name='fuente',
            field=models.CharField(choices=[('ESP32', 'Automático ESP32'), ('MANUAL', 'Ingreso manual')], default='ESP32', max_length=10),
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='registrado_por',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturasensor',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
