# Generated by Django 5.2.13 on 2026-05-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lecturasensor_fuente_lecturasensor_registrado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='comunidad',
            name='longitud',
        ),
        migrations.AddField(
            model_name='comunidad',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='pais',
            field=models.CharField(blank=True, default='Colombia', max_length=100),
        ),
    ]
