# Generated by Django 5.2.13 on 2026-05-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_comunidad_latitud_remove_comunidad_longitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
